apiVersion: apps/v1
kind: Deployment
metadata:
  name:  book-ms
  namespace: default
  labels:
    app:  book-ms
spec:
  selector:
    matchLabels:
      app: book-ms
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app:  book-ms
    spec:
      # initContainers:
        # Init containers are exactly like regular containers, except:
          # - Init containers always run to completion.
          # - Each init container must complete successfully before the next one starts.
      containers:
      - name:  book-ms
        image:  moneertv/moneer:book-ms
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 100m
            memory: 100Mi
        livenessProbe:
          tcpSocket:
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 5
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /_status/healthz
            port: 80
          initialDelaySeconds: 5
          timeoutSeconds: 2
          successThreshold: 1
          failureThreshold: 3
          periodSeconds: 10
        env:
        - name: USER_NAME
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: username
        - name: USER_PWD
          valueFrom:
            secretKeyRef:
              name: mongo-secret
              key: password 
        - name: MONGODB_URL
          valueFrom:
            configMapKeyRef:
              name: book-config
              key: mongo-url
        - name: SWAGGER_URL
          valueFrom:
            configMapKeyRef:
              name: book-config
              key: swagger-ip
        
        ports:
        - containerPort:  8000
          name:  book-ms
---
apiVersion: v1
kind: Service
metadata:
  name: book-ms-service
spec:
  selector:
    app: book-ms
  type: ClusterIP
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000